### ISSUE TITLE
Glyphs.mf error

### ISSUE THREAD

**Issue by weiweihuanghuang** [metaflop/metaflop-font-bespoke#2]
line 131: `input glyphs/punct/quoteleft`

quoteleft.mf does not exist inside glyphs/punct/

**Comment by koffeinfrei** [comment]
Hmm I'm not sure, seems to be present: https://github.com/metaflop/metaflop-font-bespoke/blob/master/glyphs/punct/quoteleft.mf. Are you on the repository's current `HEAD`?

**Comment by weiweihuanghuang** [comment]
My mistake then. I followed the submodule from metaflop-www

**Comment by koffeinfrei** [comment]
Ok let us know if you run into any further problems.
